#!/bin/bash

set -e

bash ./compile

pushd build
sleep 1
sudo -E ~/tools/bin/flasher --binary ./fk-module-dummy.bin --port /dev/$1
sleep 1
sudo -E ~/tools/bin/flasher --binary ./fk-module-dummy.bin --port /dev/$2
popd

echo
echo
echo

sleep 1
sudo -E "/bin/bash" -c "(~/tools/bin/flasher --port /dev/$1 --tail --tail-inactivity 0) | sed \"s/^/module | /\"" &
S=$!

sleep 1
sudo -E "/bin/bash" -c "(~/tools/bin/flasher --port /dev/$2 --tail --tail-inactivity 0) | sed \"s/^/  core | /\"" &
M=$!

trap ctrl_c INT

function ctrl_c() {
    echo "Killed!"
    sudo pkill flasher
}

wait $S
wait $M

